on: 
    push:
        branches:
        -   "main"
    workflow_dispatch:

jobs:
  run-java-app:
    permissions:
        security-events: write
        actions: read
        contents: read
    uses: jefremof/tsa-actions/.github/workflows/tsa-general.yml@main
    with:
        args: 'tact -c "./examples/tact/tact.config.json" -p "sample" -i "Divider"'