on:
  workflow_call:
    inputs:
      tact_config:
        required: true
        type: string
      project_name:
        required: true
        type: string
      contract_name:
        required: true
        type: string
      contract_data:
        required: false
        type: string

jobs:
  call-run-tsa-cli:
    uses: jefremof/tsa-actions/.github/workflows/tsa-general.yml@main
    with:
      args: "tact -c ${{ inputs.tact_config }} -i ${{ inputs.contract_name }} -p ${{ inputs.project_name }} ${{ inputs.contract_data && '-d' || ''}} ${{inputs.contract_data}}"