on:
    workflow_call:
      inputs:
        args:
          required: true
          type: string

jobs:
  run-tsa-cli:
    runs-on: ubuntu-22.04
    container: 
      image: explyt/tsa-env:roadmap-4

    steps:
        - name: 'Checkout repository'
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: Run TON symbolic analyzer CLI
          run: java -jar /home/tsa.jar ${{ inputs.args }} > output.sarif

        - name: Upload SARIF report
          uses: GitHub/codeql-action/upload-sarif@v2
          with:
            sarif_file: output.sarif
