on:
    workflow_call:
      inputs:
        args:
          required: true
          type: string

jobs:
  run-tsa-cli:
    runs-on: ubuntu-22.04
    permissions:
      security-events: write
      actions: read
      contents: read
    container:
      image: ghcr.io/jefremof/tsa/tsa-physical-locations:latest

    steps:
        - name: 'Checkout repository'
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: Set up timestamp
          run: |
            echo "HASH=$(echo "${{ inputs.args }}" | shasum | awk '{print $1}')" >> $GITHUB_ENV

        - name: Run TON symbolic analyzer CLI
          run: java -jar /home/tsa.jar ${{ inputs.args }} > output-${{ env.HASH }}.sarif

        - name: Upload SARIF report
          uses: GitHub/codeql-action/upload-sarif@v3
          with:
            sarif_file: output-${{ env.HASH }}.sarif